### ISSUE TITLE
Auto Assign Roles for New Members 

### ISSUE THREAD

**Issue by TimothyYLin** [LinsaneFC/RasenBot#9]
Subtask under issue #4. 

This is just so that new members that join are immediately assigned the lowest role in the server such that no member will just be under the "online" role.

**Comment by benjaminl4917** [comment]
how should we determine the lowest role in the server. should we have like a command($setDefaultRole blahblah) that sets the default role for the server because it's gonna be different for each server the bot is used on

**Comment by TimothyYLin** [comment]
We can use a default command that only administrators or mods (above a certain role that has some privilege) can use, or even better, check out guild.roles in the discord.py documentation 

![Screenshot_20220810-141449](https://user-images.githubusercontent.com/33507660/184021567-684612f3-09c2-477d-9aa2-6e4f2adf01b8.png)

**Comment by benjaminl4917** [comment]
i believe I finished this issue

**Comment by stephenlee91** [comment]
No longer needed because of housekeeping ability which provides the lowest role if they verify themselves
